### ISSUE TITLE
Docker: unable to send POST request

### ISSUE THREAD

**Issue by jppgks** [jppgks/http-client-server#26]
Introduced in #25.

`Broken pipe` when trying to POST to the server running in a Docker container, in this case on `172.17.0.2`.

```shell
$ gradle run -Pmethod=POST -Phost=172.17.0.2 -Pport=8080 -q
Enter the body of your request: 
bla

Could not write standard input into: command '/Users/joppegeluykens/anaconda3/bin/java'.
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:56)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jppgks** [comment]
Need to run containers in the same network.
Closed once README reflects this.
